name: 'Build Verilator and Iverilog'

on:
    workflow_dispatch:
        inputs:
          Upload_as_Artefact:
            description: 'Should upload the binaries as GH artefacts'
            default: false
            type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:    
    build_simulator:
        name:  build-${{ matrix.simulator }}
        runs-on: ubuntu-latest
        container:
          image: centos:7
        defaults:
          run:
            shell: bash
        strategy:
          matrix:
            simulator:
            - verilator
            - iverilog

        env:
          simulator: ${{ matrix.simulator }}

        steps:
        - name: Install Dependencies
          run: |
            yum update -y && yum group install -y 'Development Tools'
            yum install -y openssh-server openssh-clients
            yum-config-manager --enable rhel-server-rhscl-7-rpms
            yum install -y https://repo.ius.io/ius-release-el7.rpm
            yum install -y centos-release-scl
            yum install -y devtoolset-11
            yum install -y devtoolset-11-toolchain
            yum remove -y git*
            yum install -y https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
            yum install -y git wget
            yum install -y gperf python3
            python3 -m pip install --upgrade pip
            python3 -m pip install docopt
            curl -C - -O https://cmake.org/files/v3.28/cmake-3.28.0-linux-x86_64.tar.gz
            tar xzf cmake-3.28.0-linux-x86_64.tar.gz
            ln -s $PWD/cmake-3.28.0-linux-x86_64/bin/cmake /usr/bin/cmake

        - name: Checkout code
          uses: actions/checkout@v3

        - name: make workspace safe & fetch HDL simulator
          run: |
                git config --global --add safe.directory $GITHUB_WORKSPACE
                df -h && du -sch *
                cd HDL_simulator
                make build

        - name: Clone ${{ matrix.simulator }} 
          run: |
                cd HDL_simulator
                case "${{ matrix.simulator }}" in
                    "verilator")
                        git clone https://github.com/verilator/verilator.git ${{ matrix.simulator }}
                ;;
                    "iverilog")
                        git clone https://github.com/steveicarus/iverilog.git ${{ matrix.simulator }}
                ;;
                    *)
                    echo "Invalid value: ${{ matrix.simulator }}"
                ;;
                esac
                mkdir /opt/${{ matrix.simulator }}

        - name: Build ${{ matrix.simulator }} 
          run: |
                source /opt/rh/devtoolset-11/enable
                cd HDL_simulator/${{ matrix.simulator }}             
                case "${{ matrix.simulator }}" in
                    "verilator")
                        echo "for now wait !!!"
                ;;
                    "iverilog") 
                        sh autoconf.sh
                        ./configure --prefix=/opt/${{ matrix.simulator }}
                        make -j`nproc`
                        make install
                        sed -i '2i\# added by RS\nTOP_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )' /opt/${{ matrix.simulator }}/bin/iverilog-vpi
                        sed -i 's|/opt/iverilog|$TOP_DIR/..|g' /opt/${{ matrix.simulator }}/bin/iverilog-vpi
                        mv $GITHUB_WORKSPACE/HDL_simulator/build/bin/HDL_simulator/iverilog /mnt
                        cp -rf /opt/${{ matrix.simulator }} $GITHUB_WORKSPACE/HDL_simulator/build/bin/HDL_simulator/
                ;;
                    *)
                    echo "Invalid value: ${{ matrix.simulator }}"
                ;;
                esac

        - name: Run Test ${{ matrix.simulator }} 
          run: |
                source /opt/rh/devtoolset-11/enable
                cd HDL_simulator/${{ matrix.simulator }}
                case "${{ matrix.simulator }}" in
                      "verilator")
                          echo "for now wait !!!"
                  ;;
                      "iverilog")
                          export PATH=$GITHUB_WORKSPACE/HDL_simulator/build/bin/HDL_simulator/iverilog/bin:$PATH
                          bash .github/test.sh
                  ;;
                      *)
                      echo "Invalid value: ${{ matrix.simulator }}"
                  ;;
                esac

        - name: Upload Binaries
          if: ${{ matrix.simulator == 'iverilog' }}
          uses: actions/upload-artifact@v3
          with:
              name: iverilog
              path: cp -rf /opt/${{ matrix.simulator }}                

            
    Test_simulator:
        name:  Test-${{ matrix.simulator }}
        needs: build_simulator
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash
        strategy:
          fail-fast: false
          matrix:
            simulator:
            - verilator
            - iverilog

        env:
          simulator: ${{ matrix.simulator }}

        steps:
        - name: Install Dependencies
          run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install docopt

        - name: Checkout code
          uses: actions/checkout@v4

        - name: fetch HDL simulator
          run: |
                cd HDL_simulator
                make build

        - name: Download Release
          if: ${{ matrix.simulator == 'iverilog' }}
          uses: actions/download-artifact@v3
          with:
              name: iverilog

        - name: Clone ${{ matrix.simulator }} 
          run: |
                cd /mnt
                case "${{ matrix.simulator }}" in
                    "verilator")
                        echo "plz wait !!!"
                ;;
                    "iverilog")
                        git clone https://github.com/steveicarus/iverilog.git ${{ matrix.simulator }}
                        export PATH=$GITHUB_WORKSPACE/iverilog/bin:$PATH
                        iverilog -V
                        cd iverilog
                        bash .github/test.sh
                ;;
                    *)
                    echo "Invalid value: ${{ matrix.simulator }}"
                ;;
                esac

                
